name: flutter_shapes_inc
description: Simple and lightweight Flutter package for integrating with Shapes Inc AI. Easy-to-use functions for chat, multimodal messages, and AI-powered features. Enhanced image generation with smart content parsing.
version: 1.0.0
homepage: https://github.com/Ionic-Errrrs-Code/flutter_shapes
repository: https://github.com/Ionic-Errrrs-Code/flutter_shapes
issue_tracker: https://github.com/Ionic-Errrrs-Code/flutter_shapes_incissues

# Topics for better package discovery on pub.dev (max 5)
topics:
  - artificial-intelligence
  - chat
  - api
  - multimodal
  - ai-assistant

# License
license: BSD-3-Clause

# Platform support
platforms:
  android:
  ios:
  web:
  windows:
  macos:
  linux:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Core HTTP & Networking (essential)
  http: ^1.1.0
  dio: ^5.3.2
  
  # JSON & Serialization (essential)
  json_annotation: ^4.8.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true