name = "flutter-shapes-docs"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = ".vitepress/dist"

[env.production]
name = "flutter-shapes"

[env.staging]
name = "flutter-shapes-docs-staging"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build]
command = "npm run docs:build"