name = 'flutter-shapes-inc'
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

main = "workers-site/index.js"

[site]
bucket = ".vitepress/dist"

[env.production]
name = "flutter-shapes-inc"

[env.staging]
name = "flutter-shapes-inc-docs-staging"